### ISSUE TITLE
Serialization/Deserialization of Java.time.Instant

### ISSUE THREAD

**Issue by hooph00p** [arangodb/arangodb-java-driver#118]
I'm seeing a similar issue to what was observed with `UUID` serialization/deserialization before the fix. The driver is returning a `HashMap{ "seconds" -> value, "nanos" -> value}`

Can we add support for `Java.time.Instant` serialization/deserialization?

**Comment by mpv1989** [comment]
Because the driver should only require Java 6 and `java.time.Instant` is Java 8 it is only available as an extension. Since version `4.1.11` the driver supports extending the VelocyPack serialization with additional `VPackModule`s. I implemented one module for some Java 8 types. Take a look [here](https://github.com/arangodb/arangodb-java-driver#java-8-types) how to use it.

**Comment by hooph00p** [comment]
Awesome, I'll use this instead. Closing the issue.
