### ISSUE TITLE
Consider replacing JSON.simple with Jackson or any other JSON library.

### ISSUE THREAD

**Issue by PiotrFras** [arangodb/arangodb-java-driver#155]
- JSON.simple 1.1.1 is 5 year old and not supported,
- JSON.simple pulls junit and hamercrest-core as compile and runtime dependencies.

<img width="1176" alt="screen shot 2017-10-05 at 10 04 57" src="https://user-images.githubusercontent.com/24224595/31219395-0a12290e-a9b5-11e7-9f09-0dffc50d75cf.png">

**Comment by PiotrFras** [comment]
And here is the link to JSON.simple pom.xml:

https://github.com/fangyidong/json-simple/blob/tag_release_1_1_1/pom.xml

**Comment by mpv1989** [comment]
Thanks for the feedback. I am currently planning on integrating Jackson

**Comment by PiotrFras** [comment]
@mpv1989 Is there a timeline for that? Many thanks.

**Comment by mpv1989** [comment]
I hope I will find some time this month but I can't guarantee it.

**Comment by mpv1989** [comment]
@PiotrFras I took a look at it. For the release `4.2.6` I excluded junit dependency from json-simple. This should fix the dependency problem.

I have a little problem with Jackson. I took a quick look at it and as far as I see it requires java 7. I don't want to drop java 6 support with the driver now. I will investigate more as soon as I have a bit more time.

**Comment by PiotrFras** [comment]
Thanks for heads up @mpv1989.
> I don't want to drop java 6 support with the driver now.

Why not to release the driver with Jackson for JDK6?

**Comment by mpv1989** [comment]
@PiotrFras Since version 4.5.0 the driver now uses Jackson instead of JSON simple to parse json.

In addition, since version 4.5.2, you can replace the internal serializer with Jackson which allows you to use Jackson databinding with all annotations. Take a look into the [docs](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/Drivers/Java/Reference/Serialization.md#use-of-jackson-as-an-alternative-serializer) how to use it.
