### ISSUE TITLE
`java.time.Instant` is serialized as a VPack String type

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver#213]
It looks like the Java driver serializes `Instant` values (as well as `java.util.Date`) as VPack Strings rather than a VPack UTC_DATE value. This seems odd for a type like `Instant` that maps perfectly to UTC_DATE. This is with the built-in serialization with the JDK8 module:

https://github.com/arangodb/java-velocypack-module-jdk8/blob/master/src/main/java/com/arangodb/velocypack/module/jdk8/internal/util/JavaTimeUtil.java#L41

I can understand if other java.time times may be better represented as Strings or other primitives, since they may hold information that a UTC_DATE value is not capable of representing (like durations, local date/times, etc.).

**Comment by mpv1989** [comment]
Hi @rocketraman,

we serialize `Instant` and other date types to VPack String because the ArangoDB db server does not support VPack UTC_DATE within documents. For the same reason we have to serialize `byte[]` to base64 String instead of VPack binary.

Currently the ArangoDB server only supports VPack types which can be represented as Json.

**Comment by rocketraman** [comment]
Thanks for the explanation @mpv1989 . I'm assuming this is probably something that will change in the future as more of the capabilities of vpack are publicly exposed?

**Comment by mpv1989** [comment]
I think "we will see" is the most honest answer I can give you :-)

I am closing this issue because their is currently nothing to do.
