### ISSUE TITLE
arango proxy/gateway throught

### ISSUE THREAD

**Issue by zqhxuyuan** [arangodb/arangodb-java-driver#232]
as arangodb server/coordinator expose rich REST api, we want to offer an gateway just like coordinator. and in gateway, we can first forward client request to coordinator, then do sth we want.
the one of thing we want to do is add multi cluster support.

like the DC2DC replication in enterprise edition, in our implements, after gateway forward request to coordinator, we'll write data to kafka, then we has another consumer program will consume from kafka,
then replicate to another cluster.

although this function can be implement direct in coordinator, but we would use Spring to do this.
and off-course, additional gateway may increment response time from client way.

do you guys ever use something like this architecture as i thought? 

ps: another reason we want develop multi cluster support is build on only one replication.we don't want multi replication.

**Comment by dothebart** [comment]
Hi, 
The primary ArangoDB Ecosystem consists of native C++ code and Javascript code. You can add foxx services in the coordinators, however I wouln't massively talk to external (internet) resources here, since this is synchroneous.

DC2DC was implemented in GO and uses the WAL-Tailing mechanisms of the cluster components - its communicating with all of them.

The javadriver and its ecosystem sits on top of the REST interface, its not involved in the internals of ArangoDB itself.
Does that answer your question?
