### ISSUE TITLE
Q: Default value

### ISSUE THREAD

**Issue by gianluca-valentini** [arangodb/arangodb-java-driver#476]
Hi,
I'm unsing ArangoDB 3.10.1 with java driver 6.20.0.
I have 2 questions:

1. Is there a way to create a collection with a field that can have a default value if null?
2. In a graph, how I can have a AQL query that give me the the vertex (document collection) without out edge?
Thanks
Gianluca

**Comment by rashtao** [comment]
You can set default values on the server side by configuring [Computed Values](https://www.arangodb.com/docs/stable/data-modeling-documents-computed-values.html).
Otherwise you can do it on the client side using [ArangoJack Serializer](https://www.arangodb.com/docs/stable/drivers/java-reference-serialization.html) and registering a custom Jackson serializer/deserializer to handle programmatically the serialization/deserialization of the specific field.

About the second point, when writing an [AQL traversal](https://www.arangodb.com/docs/stable/aql/graphs-traversals.html) you can specify what to return, i.e. you can return only vertexes without edges.

**Comment by gianluca-valentini** [comment]
Hi @rashtao 
thanks a lot for your answer.
I look at Computed Values. It is clear for me how to implement it using java during collection creation.
using **CollectionCreateOptions** and **ComputedValue**

But how I can do it in order to update the collection?
Thanks a lot for your help
Gianluca

**Comment by rashtao** [comment]
You can change the collection properties with https://arangodb.github.io/arangodb-java-driver/javadoc-6_20/com/arangodb/ArangoCollection.html#changeProperties-com.arangodb.model.CollectionPropertiesOptions-

Nonetheless note that, as stated in https://www.arangodb.com/docs/devel/data-modeling-documents-computed-values.html#using-computed-values   

> If you add or modify computed value definitions at a later point, then they only affect subsequent write operations. Existing documents remain in their state.

Therefore already existing documents need to be manually changed, i.e. with an AQL query.

**Comment by gianluca-valentini** [comment]
Thanks a lot @rashtao

**Comment by rashtao** [comment]
Closing as inactive, please reopen in case of further questions.
