### ISSUE TITLE
Vpack for c# client

### ISSUE THREAD

**Issue by ra0o0f** [arangodb/arangodb-java-driver#52]
Hi, I'm the author of [c# driver](https://github.com/ra0o0f/arangoclient.net). I see that java driver bring Vpack for serialization. Is it better for other drivers to port Vpack in their language and use it for serialization?

**Comment by dothebart** [comment]
It depends. From my fair knowledge one is able to "translate C++ code into managed code"  which should allow using https://github.com/arangodb/velocypack/ directly inside the C# interpreter? You probably know more about this than me - however in java this would have only been possible via JNI resulting in an additional translation layer which is why we re-implented it.

**Comment by weinberger** [comment]
@ra0o0f if you could use VelocyPack and VelocyStream in the c# driver would be awesome. We will try to support you as much as possible.

**Comment by ra0o0f** [comment]
@dothebart i did not look deeply into the VPack API, but i think if c# calls many unmanaged functions for building VPack binary format for a json, then it will be worth porting it to .NET

**Comment by ra0o0f** [comment]
@weinberger absolutely, i will work on bring it to .NET driver.

**Comment by ra0o0f** [comment]
@weinberger @dothebart it's done

https://github.com/ra0o0f/velocypack.net

it's ported from java implementation(tests are passed), supports all c# primitive data types(except `decimal`) and can also serialize complex objects with a proven performance(using Json.net JsonReader/JsonWriter)
