### ISSUE TITLE
Cursor with multiple batches is closed twice

### ISSUE THREAD

**Issue by aburmeis** [arangodb/arangodb-java-driver#533]
When watching documents from the server using a cursor, this works fine if not reading to the end or the result size is below the batch size.

When fetching multiple bulks including the last, it seems the server closes the cursor itself and `ArangoCursorImpl.close()` tries this again resulting in a server error. It seems the `allowRetry` set to `true` in the constructor leads to an unused `close()`-call even it the result has no more documents.

Relates to [DE-511] #505 

If the enforced close is needed for retry, maybe passing the flag to the constructor directly from the `options.getOptions().getAllowRetry()` in `ArangoDatabaseImpl.createCursor()` would have less side effects.

[DE-511]: https://arangodb.atlassian.net/browse/DE-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aburmeis** [comment]
sorry, just saw, this seems to be a duplicate of #528

**Comment by aburmeis** [comment]
sorry, just saw, this seems to be a duplicate of #528

**Comment by rashtao** [comment]
Hi @aburmeis ,
thanks for reporting this.

When closing the cursor, the closing request is sent only if the following condition is met:
https://github.com/arangodb/arangodb-java-driver/blob/2953335ccb175d42cc351c987540d22c93a18a4b/core/src/main/java/com/arangodb/internal/cursor/ArangoCursorImpl.java#L59

and I think this is OK.

But the real problem is the (wrong) way used to derive `allowRetry`: 
https://github.com/arangodb/arangodb-java-driver/blob/2953335ccb175d42cc351c987540d22c93a18a4b/core/src/main/java/com/arangodb/internal/cursor/ArangoCursorImpl.java#L54

since also non-retriable AQL cursors could return the `nextBatchId` attribute.

To fix it, `allowRetry` should be set based on the AQL cursor creation options.

This needs to be fixed both in `ArangoCursorImpl` and `ArangoCursorAsyncImpl`.
