### ISSUE TITLE
Executing AQL using java driver with FILTER returns null

### ISSUE THREAD

**Issue by srini6teen** [arangodb/arangodb-java-driver#66]
Hi,
I am using the Java driver 4.0.0 and DB version 3.1. When I try to query, using FILTER, the ArangoCursor returns with a null element. Tried using Vpack and POJO. Neither of them work.

**Comment by mpv1989** [comment]
Hi,
the Java driver version 4.0.0 is not compatible with DB version 3.1 (only compatible with 3.1-RC1 to RC3). Upgrade to driver version 4.1.0 please.

If the error still occurs let me know. Perhaps you can post your AQL query.

**Comment by srini6teen** [comment]
Hi, 
Query - FOR u IN User FILTER u.NAME == 'SRINI' RETURN u
Ran the above Query with the following 
**DB version 3.1.RC2, Java Driver 4.1.0, query blocks and does not return any result. 
DB version 3.1.RC2, Java Driver 4.0.0, returns null element in ArangoCursor **

Query - FOR u IN User LIMIT 2 RETURN u
**DB version 3.1.RC2, Java Driver 4.1.0, query blocks and does not return any result. 
DB version 3.1.RC2, Java Driver 4.0.0, works as expected **

**Comment by mpv1989** [comment]
Ok. This is a bug in the DB in version 3.1.RC2. It is fixed in final version 3.1, which we release at the moment. It should be available in the next 1-2 days. With that version you need the driver in version 4.1.0, because we changed the velocystream protocol in the DB version 3.1, to remove the need of an extra velocystream endpoint. Driver version 4.1.0 only works with the final release and not with the RCs.

**Comment by srini6teen** [comment]
Thanks Mark. Kindly revert once 3.1 is released.
